# Generated by Django 3.2.2 on 2021-09-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod_barra',
            field=models.CharField(default=1, max_length=150, verbose_name='Código de Barra'),
            preserve_default=False,
        ),
    ]
