# Generated by Django 3.2.2 on 2021-10-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_product_cod_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.BooleanField(default=True, verbose_name='Cobranza Iva'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cod_barra',
            field=models.CharField(max_length=150, unique=True, verbose_name='Código de Barra'),
        ),
    ]
