# Generated by Django 3.2.2 on 2021-10-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20211014_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='iva',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, verbose_name='Cobranza Iva'),
        ),
    ]
