# Generated by Django 3.2.2 on 2021-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_product_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cod_barra',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Código de Barra'),
        ),
    ]
