# Generated by Django 3.2.2 on 2022-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_product_cod_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='compra/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
