# Generated by Django 3.2.2 on 2022-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_purchase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venta/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
